import React from "react";
import { CheckCircle2 } from "lucide-react";

const SECTIONS = [
  {title:"Before supplying a device — verify all of the following:",color:"#2563eb",bg:"#eff6ff",items:["Device bears the required conformity marking (CE, UKCA, ARTG, HSA, NMPA, SFDA, COFEPRIS Registro, etc.)","Manufacturer holds a valid registration, approval, or certification in the target market","Device is registered in applicable databases (EUDAMED, GUDID, ARTG, PRISM, GRLS, SFDA MDNR, etc.)","UDI is present on device label and packaging as required by the target jurisdiction","Labelling is in the required language — Japanese, Chinese, Korean, Portuguese, Russian, Spanish, Arabic as applicable","Device has not passed its expiry date; storage and transport conditions maintained","Cold chain or special storage requirements documented and maintained throughout supply","All applicable accessories, consumables, and IFU included as required"]},
  {title:"Record-keeping obligations:",color:"#16a34a",bg:"#f0fdf4",items:["Maintain records of all upstream economic operators (suppliers) and downstream customers","EU MDR / UK MHRA: keep records for minimum 10 years (15 years for implantable devices)","Record UDI information for every batch/lot of devices distributed","Document storage and transport conditions; retain cold chain records if applicable","Maintain complaint records and forward all complaints to manufacturer or authorised representative","Retain copies of CE/UKCA certificates, ARTG inclusions, SFDA MDNR approvals, and all regulatory approvals","Keep records available for regulatory authority inspection at any time without notice"]},
  {title:"When does a distributor become a manufacturer? (Triggers full manufacturer obligations)",color:"#ea580c",bg:"#fff7ed",items:["Affixing your own name, brand, or trademark to the device","Repackaging a device into different packaging affecting sterile barrier or labelling compliance","Modifying the device's intended purpose, function, or design in any way","Changing labelling in a way not authorised by the manufacturer","Adding a medicinal substance, human blood/tissue, or biological material to the device","If triggered: full manufacturer obligations apply — QMS, technical file, clinical evaluation, conformity assessment","EU MDR Art. 16 / UK MDR equivalent: limited relabelling/repackaging exemption exists with strict conditions"]},
  {title:"FSCA obligations for distributors (all jurisdictions):",color:"#dc2626",bg:"#fef2f2",items:["Immediately notify the manufacturer or authorised representative of any serious incident","Do not delay, suppress, or modify incident information before forwarding","Implement all FSCA instructions — quarantine, recall, or field correction as directed","Issue Field Safety Notices (FSNs) to customers as instructed by the manufacturer","Maintain full records of all FSCA activities, customer notifications, and return status","Cooperate fully with regulatory authority inspections related to FSCA activities","Do not supply affected devices during an active FSCA unless specifically authorised"]},
  {title:"Jurisdiction-specific distributor obligations (all 19 jurisdictions):",color:"#7c3aed",bg:"#faf5ff",items:["🇪🇺 EU MDR Art. 14: Distributors are economic operators with specific verification and record-keeping duties","🇬🇧 UK MHRA: Post-Brexit, UK distributors have equivalent obligations under UK MDR 2002 (as amended)","🇺🇸 FDA: Distributors not required to register with FDA but must maintain distribution records","🇦🇺 TGA: Distributors must deal through the Australian Sponsor; no separate distributor licence","🇸🇬 HSA: All dealers (importers, wholesalers, retailers) must hold a Dealer's Licence from HSA","🇯🇵 PMDA: Wholesale distribution business licence (Yakuji-ho) required for all Japanese distributors","🇨🇦 HC: Distributors must operate through an MDEL holder; no separate distributor registration","🇨🇭 Swissmedic: Distributors must verify MedDO compliance; similar obligations to EU MDR","🇨🇳 NMPA: Distributors must hold appropriate business licences; operate through registered NMPA Agent","🇮🇳 CDSCO: State-level distribution licences may apply depending on device type and state","🇰🇷 MFDS: Wholesale and retail dealers must hold appropriate MFDS licences","🇧🇷 ANVISA: All distributors must operate through the BRH; ANVISA records maintenance required","🇲🇾 MDA: Distributors must hold MDA Establishment Licence; verify device registration before supply","🇮🇩 BPOM: Distributors must hold PBF licence; operate through authorised importer (IT-Alkes holder)","🇻🇳 DAV: Distributors must operate through entity holding circulation registration; business licence required","🇷🇺 Roszdravnadzor: Distributors must operate through RUS REP; Russian distribution licences may apply","🇲🇽 COFEPRIS: Distributors must operate through the titular del registro; COFEPRIS records maintenance required","🇸🇦 SFDA: Distributors must operate through the Saudi AR; SFDA Dealer's Licence may be required","🇳🇿 Medsafe: No formal separate distributor licence required; must deal through registered NZ entity"]},
];

export function ToolDistrib() {
  return (
    <div>
      <div className="th-info">Distributor obligations have significantly increased globally. Non-compliance can result in distributors being deemed manufacturers with full regulatory obligations.</div>
      {SECTIONS.map(s=>(
        <div key={s.title} style={{background:s.bg,border:`1px solid ${s.color}30`,borderRadius:13,padding:18,marginBottom:12}}>
          <div style={{fontSize:13,fontWeight:700,color:s.color,marginBottom:11}}>{s.title}</div>
          {s.items.map(item=>(
            <div key={item} style={{display:"flex",gap:9,alignItems:"flex-start",marginBottom:7}}>
              <CheckCircle2 size={13} color={s.color} style={{marginTop:2,flexShrink:0}}/>
              <span style={{fontSize:13,color:"#374151",lineHeight:1.5}}>{item}</span>
            </div>
          ))}
        </div>
      ))}
    </div>
  );
}
