import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  regulationSidebar: ['intro',
    {
      type: 'category',
      label: 'Start Here',
      link: { type: 'doc', id: 'start-here/what-is-a-medical-device' },
      items: [
        'start-here/what-is-a-medical-device',
        'start-here/what-is-an-ivd',
        'start-here/what-is-not-a-medical-device',
        'start-here/borderline-products',
        'start-here/regulatory-framework',
        'start-here/anvisa-overview',
        'start-here/snvs-overview',
        'start-here/state-visa-bodies',
        'start-here/key-roles',
        'start-here/device-lifecycle',
        'start-here/mercosul-alignment',
        'start-here/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Pre-Market',
      link: { type: 'doc', id: 'pre-market/classification/how-classification-works' },
      items: [
        {
          type: 'category',
          label: 'Classification',
          link: { type: 'doc', id: 'pre-market/classification/how-classification-works' },
          items: [
            'pre-market/classification/how-classification-works',
            'pre-market/classification/class-i-ii-iii-iv',
            'pre-market/classification/classification-rules',
            'pre-market/classification/ivd-classification',
            'pre-market/classification/samd-classification',
            'pre-market/classification/borderline-combination',
            'pre-market/classification/mercosul-classification',
          ],
        },
        {
          type: 'category',
          label: 'Registration Pathway',
          link: { type: 'doc', id: 'pre-market/registration/notificacao-cadastro-registro' },
          items: [
            'pre-market/registration/notificacao-cadastro-registro',
            'pre-market/registration/notificacao',
            'pre-market/registration/cadastro',
            'pre-market/registration/registro',
            'pre-market/registration/ivd-registration',
            'pre-market/registration/peticionamento-eletronico',
            'pre-market/registration/technical-file',
            'pre-market/registration/registration-validity',
            'pre-market/registration/post-registration-changes',
            'pre-market/registration/review-process',
          ],
        },
        {
          type: 'category',
          label: 'Technical Documentation',
          link: { type: 'doc', id: 'pre-market/technical-documentation/device-description' },
          items: [
            'pre-market/technical-documentation/device-description',
            'pre-market/technical-documentation/essential-requirements',
            'pre-market/technical-documentation/risk-management',
            'pre-market/technical-documentation/biocompatibility',
            'pre-market/technical-documentation/electrical-safety-emc',
            'pre-market/technical-documentation/sterilisation',
            'pre-market/technical-documentation/software-documentation',
          ],
        },
        {
          type: 'category',
          label: 'Clinical Evidence',
          link: { type: 'doc', id: 'pre-market/clinical-evidence/overview' },
          items: [
            'pre-market/clinical-evidence/overview',
            'pre-market/clinical-evidence/clinical-investigations',
            'pre-market/clinical-evidence/ethics-approval',
            'pre-market/clinical-evidence/substantial-equivalence',
            'pre-market/clinical-evidence/foreign-clinical-data',
            'pre-market/clinical-evidence/ivd-performance-studies',
          ],
        },
        {
          type: 'category',
          label: 'Special Device Types',
          link: { type: 'doc', id: 'pre-market/special-device-types/software-samd' },
          items: [
            'pre-market/special-device-types/software-samd',
            'pre-market/special-device-types/implantable-devices',
            'pre-market/special-device-types/active-devices-inmetro',
            'pre-market/special-device-types/radiation-emitting',
            'pre-market/special-device-types/combination-products',
            'pre-market/special-device-types/single-use-devices',
            'pre-market/special-device-types/custom-devices',
            'pre-market/special-device-types/point-of-care-ivds',
            'pre-market/special-device-types/companion-diagnostics',
            'pre-market/special-device-types/systems-kits',
            'pre-market/special-device-types/exported-devices',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Post-Market',
      link: { type: 'doc', id: 'post-market/overview' },
      items: [
        'post-market/overview',
        {
          type: 'category',
          label: 'Adverse Event Reporting',
          link: { type: 'doc', id: 'post-market/adverse-events/what-must-be-reported' },
          items: [
            'post-market/adverse-events/what-must-be-reported',
            'post-market/adverse-events/reporting-timeframes',
            'post-market/adverse-events/notivisa',
            'post-market/adverse-events/annual-report',
            'post-market/adverse-events/healthcare-facility-reporting',
            'post-market/adverse-events/complaints-vs-adverse-events',
          ],
        },
        {
          type: 'category',
          label: 'Post-Market Surveillance',
          link: { type: 'doc', id: 'post-market/pms/pms-plan' },
          items: [
            'post-market/pms/pms-plan',
            'post-market/pms/complaint-handling',
            'post-market/pms/pms-report',
            'post-market/pms/pmcf',
            'post-market/pms/ivd-pmpf',
            'post-market/pms/distribution-records',
          ],
        },
        {
          type: 'category',
          label: 'Recalls & Field Safety Actions',
          link: { type: 'doc', id: 'post-market/recalls/when-required' },
          items: [
            'post-market/recalls/when-required',
            'post-market/recalls/recall-classifications',
            'post-market/recalls/field-safety-actions',
            'post-market/recalls/anvisa-mandatory-recall',
            'post-market/recalls/interdicao-apprehension',
          ],
        },
        {
          type: 'category',
          label: 'Labelling & IFU',
          link: { type: 'doc', id: 'post-market/labelling/requirements' },
          items: [
            'post-market/labelling/requirements',
            'post-market/labelling/portuguese-language',
            'post-market/labelling/electronic-ifu',
            'post-market/labelling/inmetro-marks',
            'post-market/labelling/advertising-claims',
            'post-market/labelling/expiry-lot-number',
          ],
        },
        {
          type: 'category',
          label: 'Establishment Authorisation',
          link: { type: 'doc', id: 'post-market/establishment/afe' },
          items: [
            'post-market/establishment/afe',
            'post-market/establishment/afe-types',
            'post-market/establishment/licenca-funcionamento',
            'post-market/establishment/cnpj-anvisa-registration',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'GMP & Quality System (CBPF)',
      link: { type: 'doc', id: 'gmp/overview' },
      items: [
        'gmp/overview',
        'gmp/cbpf-vs-iso13485',
        'gmp/gmp-manufacturers',
        'gmp/gmp-importers',
        'gmp/management-responsibility',
        'gmp/document-control',
        'gmp/design-development',
        'gmp/purchasing-controls',
        'gmp/production-controls',
        'gmp/sterilisation-controls',
        'gmp/capa',
        'gmp/internal-audit',
        'gmp/complaint-handling',
        'gmp/inspections',
        'gmp/auto-declaracao',
        'gmp/cbpf-certificate',
        'gmp/penalties',
      ],
    },
    {
      type: 'category',
      label: 'Importers, Distributors & Traceability',
      link: { type: 'doc', id: 'importers-distributors/importer-role' },
      items: [
        'importers-distributors/importer-role',
        'importers-distributors/afe-importers',
        'importers-distributors/responsavel-tecnico',
        'importers-distributors/import-documentation',
        'importers-distributors/siscomex-customs',
        'importers-distributors/ncm-codes',
        'importers-distributors/foreign-manufacturer-certificate',
        'importers-distributors/gmp-equivalence',
        'importers-distributors/distributor-requirements',
        'importers-distributors/storage-transport',
        'importers-distributors/distributor-recall-reporting',
        'importers-distributors/traceability-overview',
        'importers-distributors/udi-alignment',
        'importers-distributors/lot-serial-number',
        'importers-distributors/implant-records',
        'importers-distributors/snvs-traceability',
      ],
    },
    {
      type: 'category',
      label: 'Legislation & Regulations',
      link: { type: 'doc', id: 'legislation/primary-legislation' },
      items: [
        'legislation/primary-legislation',
        'legislation/rdc-751-2022',
        'legislation/rdc-752-2022',
        'legislation/rdc-753-2022',
        'legislation/rdc-754-2022',
        'legislation/rdc-755-2022',
        'legislation/rdc-10-2015',
        'legislation/rdc-36-2015',
        'legislation/normative-instructions',
        'legislation/mercosul-resolutions',
        'legislation/abnt-standards',
        'legislation/how-to-read-rdcs',
        'legislation/recent-amendments',
      ],
    },
    {
      type: 'category',
      label: 'Guidance Documents',
      link: { type: 'doc', id: 'guidance/by-topic' },
      items: [
        'guidance/by-topic',
        'guidance/by-device-type',
        'guidance/notas-tecnicas',
        'guidance/perguntas-respostas',
        'guidance/peticionamento-guides',
        'guidance/forms-templates',
        'guidance/audiencias-publicas',
      ],
    },
    {
      type: 'category',
      label: 'Special Access & Programmes',
      link: { type: 'doc', id: 'special-access/uso-compassivo' },
      items: [
        'special-access/uso-compassivo',
        'special-access/acesso-ampliado',
        'special-access/medida-cautelar',
        'special-access/bndes-finep',
        'special-access/pdp',
        'special-access/industry-associations',
      ],
    },
    {
      type: 'category',
      label: 'International & Comparison',
      link: { type: 'doc', id: 'international/overview' },
      items: [
        'international/overview',
        'international/imdrf-alignment',
        'international/anvisa-vs-others',
        'international/cfg-free-sale-certificate',
        'international/multi-market-strategy',
        'international/mercosul-roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Enforcement & Compliance',
      link: { type: 'doc', id: 'enforcement/inspections' },
      items: [
        'enforcement/inspections',
        'enforcement/state-visa-overlap',
        'enforcement/infraction-notices',
        'enforcement/fines-appeal',
        'enforcement/interdicao-seizure',
        'enforcement/registration-cancellation',
      ],
    },
    {
      type: 'category',
      label: 'Digital Health & SaMD',
      link: { type: 'doc', id: 'digital-health/framework' },
      items: [
        'digital-health/framework',
        'digital-health/samd-brazil',
        'digital-health/ai-ml-samd',
        'digital-health/mobile-health-apps',
        'digital-health/cybersecurity',
        'digital-health/lgpd-interface',
      ],
    },
    {
      type: 'category',
      label: "What's New",
      link: { type: 'doc', id: 'whats-new/regulatory-changes' },
      items: [
        'whats-new/regulatory-changes',
        'whats-new/draft-rdcs',
        'whats-new/audiencias-publicas',
        'whats-new/upcoming-changes',
        'whats-new/recall-tracker',
        'whats-new/mercosul-updates',
      ],
    },
  ],
};
export default sidebars;
