# =============================================================================
# audit_runner.py — Project 1: Website audit (GitHub Actions)
# =============================================================================
# Modes (set via env vars in the workflow):
#   RUN_ALL=true            → audit all 24 jurisdictions
#   RUN_JURISDICTION=name   → audit one specific jurisdiction
#   (neither set)           → rotation: one jurisdiction per day
# =============================================================================
import os
from datetime import datetime
from config import JURISDICTIONS, JURISDICTION_NAMES
from scraper import scrape_jurisdiction_pages
from auditor import audit_jurisdiction
from github_client import commit_report_to_private_repo


def get_todays_jurisdiction() -> tuple[str, dict]:
    day = datetime.utcnow().timetuple().tm_yday
    idx = (day - 1) % len(JURISDICTION_NAMES)
    name = JURISDICTION_NAMES[idx]
    return name, JURISDICTIONS[name]


def build_report(jurisdiction: str, rapath_url: str, audit: dict) -> str:
    today = datetime.utcnow().strftime("%Y-%m-%d")

    def fmt_content_updates(items):
        if not items:
            return "_None found._\n"
        out = ""
        for i, item in enumerate(items, 1):
            if isinstance(item, dict):
                out += f"**{i}. {item.get('issue', 'Issue')}**\n"
                out += f"- **Page:** {item.get('page', 'Unknown')}\n"
                out += f"- **Add this:**\n\n> {item.get('suggested_addition', '').strip()}\n\n"
            else:
                out += f"- {item}\n"
        return out

    def fmt_errors(items):
        if not items:
            return "_None found._\n"
        out = ""
        for i, item in enumerate(items, 1):
            if isinstance(item, dict):
                out += f"**{i}. {item.get('page', 'Unknown')}**\n"
                out += f"- **Current:** `{item.get('original_text', '').strip()}`\n"
                out += f"- **Replace with:** `{item.get('corrected_text', '').strip()}`\n\n"
            else:
                out += f"- {item}\n"
        return out

    def fmt_improvements(items):
        if not items:
            return "_None found._\n"
        out = ""
        for i, item in enumerate(items, 1):
            if isinstance(item, dict):
                out += f"**{i}. {item.get('page', 'Unknown')}**\n"
                out += f"- **Current:** `{item.get('original_text', '').strip()}`\n"
                out += f"- **Rewrite as:** `{item.get('improved_text', '').strip()}`\n\n"
            else:
                out += f"- {item}\n"
        return out

    return f"""# Audit Report — {jurisdiction}
**Date:** {today}
**Site:** [{rapath_url}]({rapath_url})

---

## 🔴 Content Updates / Missing Information
{fmt_content_updates(audit.get('content_updates', []))}
## 🟡 Accuracy Errors & Text Corrections
{fmt_errors(audit.get('accuracy_errors', []))}
## 🟢 Suggested Improvements & Clarity
{fmt_improvements(audit.get('improvements', []))}

---
_Generated by RAPath Auditor using Claude Haiku. Review all suggestions before applying._
"""


def get_target_jurisdictions() -> dict:
    """Determine which jurisdictions to audit based on environment variables."""
    run_all = os.environ.get("RUN_ALL", "false").lower() == "true"
    specific = os.environ.get("RUN_JURISDICTION", "").strip()

    if run_all:
        print("Mode: ALL 24 jurisdictions")
        return JURISDICTIONS
    elif specific and specific in JURISDICTIONS:
        print(f"Mode: Single jurisdiction — {specific}")
        return {specific: JURISDICTIONS[specific]}
    else:
        name, urls = get_todays_jurisdiction()
        print(f"Mode: Rotation — today's jurisdiction is {name}")
        return {name: urls}


def main():
    today = datetime.utcnow().strftime("%Y-%m-%d")
    print(f"RAPath Audit — {today}")

    target = get_target_jurisdictions()
    print(f"Auditing {len(target)} jurisdiction(s)\n")

    for jurisdiction, urls in target.items():
        print(f"\n--- {jurisdiction} ---")

        # Scrape
        pages = scrape_jurisdiction_pages(urls["sitemap_url"], urls["rapath_url"])

        # Audit
        print("  Sending to Claude Haiku...")
        audit = audit_jurisdiction(jurisdiction, pages)

        n1 = len(audit.get("content_updates", []))
        n2 = len(audit.get("accuracy_errors", []))
        n3 = len(audit.get("improvements", []))
        print(f"  Found: {n1} content gaps, {n2} errors, {n3} improvements")

        # Build and save report
        report_md = build_report(jurisdiction, urls["rapath_url"], audit)
        slug = jurisdiction.lower().replace(" ", "-").replace("(", "").replace(")", "")
        filename = f"reports/{today}-{slug}.md"

        commit_report_to_private_repo(
            filename=filename,
            content=report_md,
            message=f"Audit: {jurisdiction} — {today}"
        )

    print("\nAll done.")


if __name__ == "__main__":
    main()
