# =============================================================================
# audit_runner.py — Project 1: Daily website audit (GitHub Actions)
# =============================================================================
# Rotates through 24 jurisdictions (one per day) using day-of-year.
# Audits via Claude Haiku, commits markdown report to private audit-reports repo.
# =============================================================================
from datetime import datetime
from config import JURISDICTIONS, JURISDICTION_NAMES
from scraper import scrape_jurisdiction_pages
from auditor import audit_jurisdiction
from github_client import commit_report_to_private_repo


def get_todays_jurisdiction() -> tuple[str, dict]:
    day = datetime.utcnow().timetuple().tm_yday
    idx = (day - 1) % len(JURISDICTION_NAMES)
    name = JURISDICTION_NAMES[idx]
    return name, JURISDICTIONS[name]


def build_report(jurisdiction: str, rapath_url: str, audit: dict) -> str:
    today = datetime.utcnow().strftime("%Y-%m-%d")

    def fmt_content_updates(items):
        if not items:
            return "_None found._\n"
        out = ""
        for i, item in enumerate(items, 1):
            if isinstance(item, dict):
                out += f"**{i}. {item.get('issue', 'Issue')}**\n"
                out += f"- **Page:** {item.get('page', 'Unknown')}\n"
                out += f"- **Add this:**\n\n> {item.get('suggested_addition', '').strip()}\n\n"
            else:
                out += f"- {item}\n"
        return out

    def fmt_errors(items):
        if not items:
            return "_None found._\n"
        out = ""
        for i, item in enumerate(items, 1):
            if isinstance(item, dict):
                out += f"**{i}. {item.get('page', 'Unknown')}**\n"
                out += f"- **Current:** `{item.get('original_text', '').strip()}`\n"
                out += f"- **Replace with:** `{item.get('corrected_text', '').strip()}`\n\n"
            else:
                out += f"- {item}\n"
        return out

    def fmt_improvements(items):
        if not items:
            return "_None found._\n"
        out = ""
        for i, item in enumerate(items, 1):
            if isinstance(item, dict):
                out += f"**{i}. {item.get('page', 'Unknown')}**\n"
                out += f"- **Current:** `{item.get('original_text', '').strip()}`\n"
                out += f"- **Rewrite as:** `{item.get('improved_text', '').strip()}`\n\n"
            else:
                out += f"- {item}\n"
        return out

    return f"""# Audit Report — {jurisdiction}
**Date:** {today}
**Site:** [{rapath_url}]({rapath_url})

---

## 🔴 Content Updates / Missing Information
{fmt_content_updates(audit.get('content_updates', []))}
## 🟡 Accuracy Errors & Text Corrections
{fmt_errors(audit.get('accuracy_errors', []))}
## 🟢 Suggested Improvements & Clarity
{fmt_improvements(audit.get('improvements', []))}

---
_Generated by RAPath Auditor using Claude Haiku. Review all suggestions before applying._
"""


def main():
    jurisdiction, urls = get_todays_jurisdiction()
    today = datetime.utcnow().strftime("%Y-%m-%d")

    print(f"RAPath Audit — {today}")
    print(f"Jurisdiction: {jurisdiction}")

    # Scrape
    pages = scrape_jurisdiction_pages(urls["sitemap_url"], urls["rapath_url"])

    # Audit
    print("  Sending to Claude Haiku...")
    audit = audit_jurisdiction(jurisdiction, pages)

    n1 = len(audit.get("content_updates", []))
    n2 = len(audit.get("accuracy_errors", []))
    n3 = len(audit.get("improvements", []))
    print(f"  Found: {n1} content gaps, {n2} errors, {n3} improvements")

    # Build and save report
    report_md = build_report(jurisdiction, urls["rapath_url"], audit)
    # Use jurisdiction slug for filename
    slug = jurisdiction.lower().replace(" ", "-").replace("(", "").replace(")", "")
    filename = f"reports/{today}-{slug}.md"

    commit_report_to_private_repo(
        filename=filename,
        content=report_md,
        message=f"Audit: {jurisdiction} — {today}"
    )

    print("Done.")


if __name__ == "__main__":
    main()
